
---
- name: Use ansible to build the dev enviornment.
  hosts: controller-only
  vars:
      #ansible_user: eventsadmusr
  tasks:
  - name: run the service defined in my_project's docker-compose.yml
    docker_compose:
      project_src: .
